// sidraw_rom.v
// BRAM-baked .sidraw byte source for first-silicon bring-up of the
// .sidraw playback path. Streams the bytes of a pre-generated .sidraw
// file (test_tune.hex, generated by `sw/sidraw_to_hex.py`) over a
// vld/rdy handshake. After the last byte is consumed, `byte_vld` drops
// to 0 (the downstream sidraw_player will hit its 0xFF EOF byte and
// transition to DONE).
//
// This is a bring-up artefact. The runtime path (step 7 in
// PLANNING.md) replaces this with a FIFO fed by MiST `data_io`.
//
// BRAM inference notes (Quartus 13.1 / Cyclone III M9K):
//   - The read must be in its own clk-only always block, with NO reset
//     on the output register (M9K can't reset its internal output).
//   - The read must be a single unconditional `<= mem[addr]`.
//   - Mixing the read into the streaming FSM's conditional logic --
//     which the first version of this file did -- causes Quartus to
//     fall back to LUT-based ROM, exploding LE count by ~11 kLEs.
//   - The streaming FSM here drives `rd_addr` and accepts a 1-cycle
//     read latency, giving 0.5 byte/cycle throughput. That's plenty
//     for sidraw_player (which spends most of its time in WAIT).
//
// 2026, Rok Krajnc <rok.krajnc@gmail.com>


`default_nettype none


module sidraw_rom #(
  parameter         MIF_FILE   = "test_tune.hex",
  parameter integer DEPTH      = 39643,                 // size of .sidraw in bytes
  parameter integer ADDR_WIDTH = 16                     // ceil(log2(DEPTH))
) (
  input  wire        clk,
  input  wire        rst_n,           // async, active low

  // byte-stream output (consumer is sidraw_player)
  output wire [ 7:0] byte_dat,
  output wire        byte_vld,
  input  wire        byte_rdy
);


//// inferred M9K ROM: must be the *only* thing in this always block, no
// reset, no conditional. Quartus matches this against its sync-ROM
// template and maps to M9K. The mem array is sized to a power of 2 so
// the inferred memory depth matches the address space.
reg [7:0] mem [0:(1<<ADDR_WIDTH)-1];
initial $readmemh(MIF_FILE, mem);

reg [ADDR_WIDTH-1:0] rd_addr;
reg [           7:0] rd_data;

always @(posedge clk) begin
  rd_data <= mem[rd_addr];
end


//// streaming FSM ////
// State semantics:
//   PUMP: just out of reset; the BRAM is loading mem[0] this cycle.
//         Next cycle, data is visible; transition to PRESENT.
//   PRESENT: byte_vld=1, byte_dat reflects mem[rd_addr] (which equals
//            the current visible byte position). Wait for handshake.
//            On handshake, advance rd_addr and drop byte_vld for one
//            cycle while the BRAM loads the next byte.
//   REFILL: BRAM is loading mem[rd_addr] (the byte we just advanced
//           to). One cycle later, data is visible; back to PRESENT.
//   DONE:   end of buffer reached. byte_vld stays 0.
localparam [1:0] ST_PUMP    = 2'd0;
localparam [1:0] ST_PRESENT = 2'd1;
localparam [1:0] ST_REFILL  = 2'd2;
localparam [1:0] ST_DONE    = 2'd3;

reg [1:0]            state;
reg [ADDR_WIDTH:0]   vis_pos;       // byte position currently visible (1 spare bit for end-detect)
reg                  vld_r;

always @(posedge clk, negedge rst_n) begin
  if (!rst_n) begin
    state   <= ST_PUMP;
    rd_addr <= {ADDR_WIDTH{1'b0}};
    vis_pos <= {(ADDR_WIDTH+1){1'b0}};
    vld_r   <= 1'b0;
  end else begin
    case (state)
      ST_PUMP: begin
        // BRAM loaded mem[0] this cycle; expose next cycle.
        vld_r <= 1'b1;
        state <= ST_PRESENT;
      end
      ST_PRESENT: begin
        if (byte_rdy) begin
          // handshake: advance to the next byte
          if (vis_pos + {{ADDR_WIDTH{1'b0}}, 1'b1} >= DEPTH[ADDR_WIDTH:0]) begin
            vld_r <= 1'b0;
            state <= ST_DONE;
          end else begin
            vis_pos <= vis_pos + {{ADDR_WIDTH{1'b0}}, 1'b1};
            rd_addr <= rd_addr + {{(ADDR_WIDTH-1){1'b0}}, 1'b1};
            vld_r   <= 1'b0;       // mark stale while BRAM loads next
            state   <= ST_REFILL;
          end
        end
      end
      ST_REFILL: begin
        // BRAM is loading mem[rd_addr] this cycle; visible next cycle.
        vld_r <= 1'b1;
        state <= ST_PRESENT;
      end
      ST_DONE: begin
        // stay here; vld_r is 0
      end
      default: state <= ST_DONE;
    endcase
  end
end

assign byte_dat = rd_data;
assign byte_vld = vld_r;


endmodule


`default_nettype wire
